### ISSUE TITLE
Warnings when compiling  Armbianio

### ISSUE THREAD

**Issue by R4C3R** [bitbank2/ArmbianIO#13]
I just cloned the ArmbianIO repo and used make to compile on my NanoPi Neo 2 (clean Armbian install + apt update/upgrade) but received two warnings in the process:

armbianio.c: In function ‘GPIOThread’:
armbianio.c:460:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 int iPin = (int)param; // pin number is passed in
            ^
armbianio.c: In function ‘AIOAddGPIOCallback’:
armbianio.c:520:43: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  pthread_create(&tinfo, NULL, GPIOThread, (void *)iPin);

**Comment by sgjava** [comment]
Hmmmm, what architecture are you building under?

**Comment by R4C3R** [comment]
That could be it, The NanoPi Neo 2 uses the H5 Allwinner SOC, which is a 64-Bit Cortex A53.

This is the linux version I'm using:

ARMBIAN 5.38 stable Debian GNU/Linux 9 (stretch) 4.14.18-sunxi64

downloaded directly from the Armbian website: https://www.armbian.com/nanopi-neo-2/

**Comment by sgjava** [comment]
I'm working on a major upgrade to one of my projects, so I cannot dig into this right now. If you want to try https://github.com/sgjava/userspaceio I know it works with 32/64 bit ARM. If you are using kernel >= 4.16 everything works without sudo.

**Comment by bitbank2** [comment]
Those warnings are completely benign and can be ignored. Why is this even an issue?

**Comment by sgjava** [comment]
Probably not an issue.
