### ISSUE TITLE
not working on RPi's

### ISSUE THREAD

**Issue by wabmester** [bitbank2/ArmbianIO#17]
Tried the demo on a Pi 3B+ and a Pi Zero WH.   Both errored thusly:

Unrecognized board type, aborting...
Problem initializing ArmbianIO library

uname: Linux servo 5.4.83-v7+ 

FWIW, there is no /run/machine-id with this kernel.

**Comment by wabmester** [comment]
It looks like others are determining board type via /proc/cpuinfo.    Here's a dump from the Pi Zero:

cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 000000005d9860ef
Model           : Raspberry Pi Zero W Rev 1.1

**Comment by bitbank2** [comment]
For the RPI models, instead of calling AIOInit(),  call AIOInitBoard("Raspberry Pi");
