### ISSUE TITLE
RPi.GPIO wrapper plans?

### ISSUE THREAD

**Issue by sgjava** [bitbank2/ArmbianIO#2]
Any plans to write RPi.GPIO wrapper since a lot of Python libraries depend on it.

**Comment by bitbank2** [comment]
I don't 'do' Python. You're welcome to take my code and add what's needed to allow access from Python.

**Comment by sgjava** [comment]
OK, I might just wrap libgpiod since that seems to be the generic way to go.

**Comment by sgjava** [comment]
OK, I generated a wrapper with Swig today, so the following works to light up a LED on NanoPi Duo:
```
import time
from ArmbianIO import *

rc = AIOInit()
if rc == 1:
    AIOAddGPIO(12, GPIO_OUT)
    AIOWriteGPIO(12, 0)
    time.sleep(3)
    AIOWriteGPIO(12, 1)
    AIOShutdown()
else:
    print "AIOInit error"
```

I'll do a PR with documentation of how to generate. This will make it easier to create a RPi.GPIO clone!
