### ISSUE TITLE
Release on maven repository

### ISSUE THREAD

**Issue by Son-kun** [bitbank2/ArmbianIO#25]
Do you consider to release armbianIO as a project on official maven repository?

**Comment by bitbank2** [comment]
I haven't used this code in a long time and am not currently working on any Linux projects. What's the official Maven repo and why would I need to release this there?

**Comment by melroy89** [comment]
I think he means: https://mvnrepository.com/ ... But that is a centralized repo for Java projects. Since ArmbianIO is NOT Java (thank God, except for: https://github.com/bitbank2/ArmbianIO/tree/master/java), I don't see why this is relevant unless he is aiming for this Java interface.
